 
sudo: false

language: node_js

# cache:
#   directories:
#     - node_modules

node_js:
  - node

before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

branches:
  only:
    - master

install: 
  - npm ci


script:
  - npm run test:coveralls 



 
  